# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2620a9636dbd21201686177bb3c390f0b23523cc7bd5252ead941b6b6d03b59038ee88c513744b170ccd5f8a6c108bd370b45e48f3052fcea68867e29f85b1a0

test:
  secret_key_base: 52a38798c5a34b81c2cb0f72cfc6c99c64682e04b9210c030fd3f03175dd4149b56d7182c3cbac4574420a663b75d2b4ab458c31ad73d02cfcfc97b2a9298e59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
